name: Android CI

on:
  push:
    branches:
    - '5.**'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Remove Android 31 (S)
      run: $ANDROID_HOME/tools/bin/sdkmanager --uninstall "platforms;android-31"

    - name: Build with Gradle
      run: ./gradlew assemblePlayProdRelease

    - name: Get version
      id: get-version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/}

    - name: Sign APKs
      env:
        # If you want to generate a keystore secret, run these commands:
        # keytool -genkey -v -keystore apksign.keystore -alias apksign -keyalg RSA -keysize 4096
        # cat apksign.keystore | base64
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      run: |
        echo "${KEYSTORE_BASE64}" | base64 -d > apksign.keystore
        for apk in app/build/outputs/apk/playProd/release/*-unsigned-*.apk; do
        out=${apk/-unsigned-/-signed-}
        ${ANDROID_HOME}/build-tools/30.0.2/apksigner sign --ks apksign.keystore --ks-pass env:KEYSTORE_PASS --out "${out}" "${apk}"
        echo "$(sha256sum ${out})"
        done
        rm apksign.keystore
