name: Remote Desktop

on:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: cd reproducible-builds && docker build -t signal-android . && cd ..

    - name: docker
      run: docker run --rm -v $(pwd):/project -w /project signal-android ./gradlew clean assemblePlayProdRelease
